# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: env
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - production
      - staging

trigger: none

pr: none

variables:
  - group: tf-vars

pool:
  vmImage: ubuntu-latest


stages:
  - stage: infra_destroy
    displayName: "terraform_destroy"
    jobs:
      - job: terraform_destroy_steps 
        steps:     
        - script: |
              set -e
              terraform init -input=false -backend-config=key=${{ parameters.env }}.tfstate
              terraform destroy -input=false -var-file=${{ parameters.env }}.tfvars -auto-approve
          env:
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
