# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: env
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - prod

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Provision
    displayName: "Terraforming"
    variables:
    - group: tf-vars
    jobs:
      - job: terraform-steps
        steps:     
        - script: |
              set -e
              terraform init -input=false
              terraform apply -input=false -auto-approve


